// Code generated by "stringer --type Kind"; DO NOT EDIT.

package tnrpt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNKNOWN-0]
	_ = x[BACKSLASH-1]
	_ = x[COLON-2]
	_ = x[COMMA-3]
	_ = x[DASH-4]
	_ = x[DOT-5]
	_ = x[EQUALS-6]
	_ = x[HASH-7]
	_ = x[LEFTPAREN-8]
	_ = x[RIGHTPAREN-9]
	_ = x[SINGLEQUOTE-10]
	_ = x[SLASH-11]
	_ = x[SPACE-12]
	_ = x[Courier-13]
	_ = x[Current-14]
	_ = x[Direction-15]
	_ = x[Element-16]
	_ = x[Fleet-17]
	_ = x[Garrison-18]
	_ = x[Goes-19]
	_ = x[Grid-20]
	_ = x[Hex-21]
	_ = x[Move-22]
	_ = x[Movement-23]
	_ = x[NA-24]
	_ = x[Next-25]
	_ = x[Note-26]
	_ = x[Number-27]
	_ = x[Previous-28]
	_ = x[Scout-29]
	_ = x[ScoutId-30]
	_ = x[Season-31]
	_ = x[Status-32]
	_ = x[TerrainCode-33]
	_ = x[Text-34]
	_ = x[To-35]
	_ = x[Tribe-36]
	_ = x[Turn-37]
	_ = x[TurnYearMonth-38]
	_ = x[UnitId-39]
	_ = x[Weather-40]
	_ = x[EndOfLine-41]
	_ = x[EndOfInput-42]
}

const _Kind_name = "UNKNOWNBACKSLASHCOLONCOMMADASHDOTEQUALSHASHLEFTPARENRIGHTPARENSINGLEQUOTESLASHSPACECourierCurrentDirectionElementFleetGarrisonGoesGridHexMoveMovementNANextNoteNumberPreviousScoutScoutIdSeasonStatusTerrainCodeTextToTribeTurnTurnYearMonthUnitIdWeatherEndOfLineEndOfInput"

var _Kind_index = [...]uint16{0, 7, 16, 21, 26, 30, 33, 39, 43, 52, 62, 73, 78, 83, 90, 97, 106, 113, 118, 126, 130, 134, 137, 141, 149, 151, 155, 159, 165, 173, 178, 185, 191, 197, 208, 212, 214, 219, 223, 236, 242, 249, 258, 268}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
