// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
// Copyright (c) 2025 Michael D Henderson. All rights reserved.

package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "encoding/json"

type GameOption struct {
	ID          string
	Description string
	Turns       []GameTurnOption
}
type GameTurnOption struct {
	ID       string
	IsActive bool
}

func turnsToJSON(turns []GameTurnOption) string {
	data, err := json.Marshal(turns)
	if err != nil {
		return "[]"
	}
	return string(data)
}

func UploadPage(data LayoutData, games []GameOption, selectedGame string, turns []int, selectedTurn int) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"upload-container\"><h1>Upload Turn Reports</h1><p>Upload turn reports for processing. Files must be named <code>CCCC.docx</code> or <code>GGGG.YYYY-MM.CCCC.report.txt</code>.</p><div class=\"upload-config\"><div class=\"form-group\"><label for=\"game-select\">Game</label> <select id=\"game-select\" name=\"game\" required><option value=\"\">Select a game...</option> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, g := range games {
				if g.ID == selectedGame {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<option value=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var3 string
					templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(g.ID)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/upload.templ`, Line: 37, Col: 28}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" selected data-turns=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var4 string
					templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(turnsToJSON(g.Turns))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/upload.templ`, Line: 37, Col: 73}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var5 string
					templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(g.Description)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/upload.templ`, Line: 37, Col: 91}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</option>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				} else {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<option value=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var6 string
					templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(g.ID)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/upload.templ`, Line: 39, Col: 28}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\" data-turns=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var7 string
					templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(turnsToJSON(g.Turns))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/upload.templ`, Line: 39, Col: 64}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var8 string
					templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(g.Description)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/upload.templ`, Line: 39, Col: 82}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</option>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</select></div><div class=\"form-group\"><label for=\"turn-select\">Turn Number</label> <select id=\"turn-select\" name=\"turn\" required><option value=\"\">Select a turn...</option></select></div></div><div id=\"drop-zone\" class=\"drop-zone\"><div class=\"drop-zone-content\"><p class=\"drop-icon\">📁</p><p>Drag & drop files here</p><p class=\"drop-hint\">or click to select files</p><input type=\"file\" id=\"file-input\" multiple accept=\".docx,.txt\" style=\"display:none\"></div></div><div id=\"upload-list\" class=\"upload-list\"></div></div><div id=\"toast-container\" class=\"toast-container\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = uploadScript().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = LayoutWithData("Upload Reports", data).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func uploadScript() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_uploadScript_5070`,
		Function: `function __templ_uploadScript_5070(){const dropZone = document.getElementById('drop-zone');
	const fileInput = document.getElementById('file-input');
	const uploadList = document.getElementById('upload-list');
	const toastContainer = document.getElementById('toast-container');
	const gameSelect = document.getElementById('game-select');
	const turnSelect = document.getElementById('turn-select');

	// Update turn dropdown when game changes
	gameSelect.addEventListener('change', () => {
		updateTurnDropdown();
		updateDropZoneState();
	});

	// Update drop zone state when turn changes
	turnSelect.addEventListener('change', () => {
		updateDropZoneState();
	});

	function updateDropZoneState() {
		const isEnabled = gameSelect.value !== '' && turnSelect.value !== '';
		if (isEnabled) {
			dropZone.classList.remove('disabled');
			dropZone.style.opacity = '1';
			dropZone.style.cursor = 'pointer';
			dropZone.style.pointerEvents = 'auto';
		} else {
			dropZone.classList.add('disabled');
			dropZone.style.opacity = '0.5';
			dropZone.style.cursor = 'not-allowed';
			dropZone.style.pointerEvents = 'none';
		}
	}

	// Click to select files
	dropZone.addEventListener('click', () => {
		if (gameSelect.value !== '' && turnSelect.value !== '') {
			fileInput.click();
		}
	});

	// Drag and drop handlers
	dropZone.addEventListener('dragover', (e) => {
		e.preventDefault();
		dropZone.classList.add('drag-over');
	});

	dropZone.addEventListener('dragleave', (e) => {
		e.preventDefault();
		dropZone.classList.remove('drag-over');
	});

	dropZone.addEventListener('drop', (e) => {
		e.preventDefault();
		dropZone.classList.remove('drag-over');
		handleFiles(e.dataTransfer.files);
	});

	fileInput.addEventListener('change', (e) => {
		handleFiles(e.target.files);
	});

	function updateTurnDropdown() {
		const selectedOption = gameSelect.options[gameSelect.selectedIndex];
		const turnsJSON = selectedOption.getAttribute('data-turns') || '[]';
		const turns = JSON.parse(turnsJSON);
		console.log(turns);

		turnSelect.innerHTML = '<option value="">Select a turn...</option>';

		if (turns.length === 0) {
			return;
		}

		// Find first active turn (if any) or first turn
		let defaultTurnNo = null;
		for (const turn of turns) {
		    if (turn.IsActive) {
		        defaultTurnNo = turn.ID;
            }
		}

		// Populate dropdown
		for (const turn of turns) {
			const option = document.createElement('option');
			option.value = turn.ID;
			option.textContent = turn.ID;
			option.selected = turn.ID === defaultTurnNo;
			turnSelect.appendChild(option);
		}
	}

	// Initialize turn dropdown if game is already selected
	if (gameSelect.value) {
		updateTurnDropdown();
	}

	// Initialize drop zone state
	updateDropZoneState();

	function handleFiles(files) {
		const game = gameSelect.value;
		const turn = turnSelect.value;

		if (!game) {
			showToast('Please select a game first.', 'info');
			return;
		}
		if (!turn) {
			showToast('Please select a turn number first.', 'info');
			return;
		}

		uploadList.innerHTML = '';

		for (const file of files) {
			uploadFile(file, game, turn);
		}
	}

	function uploadFile(file, game, turn) {
		const item = document.createElement('div');
		item.className = 'upload-item';
		item.innerHTML = ` + "`" + `
			<span class="upload-name">${file.name}</span>
			<span class="upload-status uploading">Uploading...</span>
			<div class="upload-progress"><div class="upload-progress-bar"></div></div>
		` + "`" + `;
		uploadList.appendChild(item);

		const progressBar = item.querySelector('.upload-progress-bar');
		const status = item.querySelector('.upload-status');

		const formData = new FormData();
		formData.append('file', file);
		formData.append('game', game);
		formData.append('turn', turn);

		const xhr = new XMLHttpRequest();
		xhr.open('POST', '/upload');

		xhr.upload.onprogress = (e) => {
			if (e.lengthComputable) {
				const pct = (e.loaded / e.total) * 100;
				progressBar.style.width = pct + '%';
			}
		};

		xhr.onload = () => {
			if (xhr.status === 200) {
				const resp = JSON.parse(xhr.responseText);
				status.textContent = '✓ Success';
				status.className = 'upload-status success';
				showToast(` + "`" + `<strong>${file.name}</strong><br>Parsed ${resp.units || 0} units, ${resp.acts || 0} acts, ${resp.steps || 0} steps.` + "`" + `, 'success');
			} else {
				let msg = 'Upload failed';
				try {
					const resp = JSON.parse(xhr.responseText);
					msg = resp.error || msg;
				} catch {}
				status.textContent = '✗ ' + msg;
				status.className = 'upload-status error';
				showToast(` + "`" + `<strong>${file.name}</strong><br>${msg}` + "`" + `, 'error', 8000);
			}
		};

		xhr.onerror = () => {
			status.textContent = '✗ Network error';
			status.className = 'upload-status error';
			showToast(` + "`" + `<strong>${file.name}</strong><br>Network error` + "`" + `, 'error', 8000);
		};

		xhr.send(formData);
	}

	function showToast(message, type = 'info', duration = 5000) {
		const icons = {
			success: '✓',
			error: '✗',
			info: 'ℹ'
		};

		const toast = document.createElement('div');
		toast.className = ` + "`" + `toast toast-${type}` + "`" + `;
		toast.innerHTML = ` + "`" + `
			<span class="toast-icon">${icons[type]}</span>
			<div class="toast-content">${message}</div>
			<button class="toast-close" aria-label="Close">×</button>
		` + "`" + `;

		const closeBtn = toast.querySelector('.toast-close');
		closeBtn.addEventListener('click', () => dismissToast(toast));

		toastContainer.appendChild(toast);

		setTimeout(() => dismissToast(toast), duration);
	}

	function dismissToast(toast) {
		if (toast.classList.contains('toast-hiding')) return;
		toast.classList.add('toast-hiding');
		setTimeout(() => toast.remove(), 300);
	}
}`,
		Call:       templ.SafeScript(`__templ_uploadScript_5070`),
		CallInline: templ.SafeScriptInline(`__templ_uploadScript_5070`),
	}
}

var _ = templruntime.GeneratedTemplate
